create view vw_lsoa as
select
    l.lsoacd,
    l.lsoanm,
    p.population,
    i.imd_rank,
    i.imd_decile,
    i.income_rank,
    i.income_decile,
    i.employment_rank,
    i.employment_decile,
    i.education_rank,
    i.education_decile,
    i.health_rank,
    i.health_decile,
    i.crime_rank,
    i.crime_decile,
    i.housing_rank,
    i.housing_decile,
    i.environment_rank,
    i.environment_decile,
    i.idaci_rank,
    i.idaci_decile,
    i.idaopi_rank,
    i.idaopi_decile,
    i.children_rank,
    i.children_decile,
    i.adultskills_rank,
    i.adultskills_decile,
    i.geographical_rank ,
    i.geographical_decile,
    i.wider_rank,
    i.wider_decile ,
    i.indoors_rank,
    i.indoors_decile,
    i.outdoors_rank,
    i.outdoors_decile,
    l.geom,
    l.geom_generalised
from lsoa_boundary l
join lsoa_imd i on i.lsoa_code = l.lsoacd
join lsoa_population p on p.lsoacd = l.lsoacd;