create table postcode_lookups (
    postcode_7 character (7),
    postcode_8 character (8),
    postcode character varying (10),
    date_of_introduction character (6),
    date_of_termination character (6),
    user_type integer,
    easting numeric,
    northing numeric,
    positional_quality_indicator integer,
    oa character (9),
    county character (9),
    county_electoral_division character (9),
    district character (9),
    ward character (9),
    health_area character (9),
    nhs_region character (9),
    country character (9),
    region character (9),
    parliamentary_constituency character (9),
    european_electoral_region character (9),
    learning_region character (9),
    travel_to_work_area character (9),
    primary_care_trust character (9),
    nuts character (9),
    park character (9),
    lsoa character (9),
    msoa character (9),
    workplace_zone character (9),
    clinical_commissioning_group character (9),
    built_up_area character (9),
    built_up_area_subdivision character (9),
    rural_urban_classification character varying (2),
    oa_classification character (9),
    latitude numeric,
    longitude numeric,
    local_enterprise_partnership_1 character (9),
    local_enterprise_partnership_2 character (9),
    police_force_area character (9),
    imd integer,
    cancer_alliance character (9),
    sustainability_transformation_partnership character (9)
);
